import type { Metadata } from "next";
import Navbar from "@/layout/admin/Navbar";
import Sidebar from "@/layout/admin/Sidebar";


export const metadata: Metadata = {
  title: "Clinic Admin Pannel",
  description: "Generated by Debdut",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className="flex flex-col">
    <Navbar/>
    <div className="flex flex-row gap-2">
        <Sidebar/>
           {children}
    </div>
   </div>
     

  );
}
